development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  host: localhost
  port: 3306
  database:
  username:
  password:
  charset: utf8
  collation: utf8_bin
  pool: 5